Models/AppDbContext.cs
using Microsoft.EntityFrameworkCore;
using TaskManagment.Models.Entites;

namespace TaskManagment.Models
{
    public class AppDbContext:DbContext
    {
        public AppDbContext(DbContextOptions<AppDbContext> options):base(options)
        {
            
        }
        public DbSet<User> users { get; set; }
        public DbSet <Project> projects { get; set; }
        public DbSet<task> tasks { get; set; }
        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<task>().HasOne(x => x.User).WithMany(x => x.Tasks).HasForeignKey(x => x.Userid).OnDelete(DeleteBehavior.NoAction);
            modelBuilder.Entity<task>().HasOne(x => x.Project).WithMany(x => x.Tasks).HasForeignKey(x => x.Projectid).OnDelete(DeleteBehavior.NoAction);
        }
    }
}

Models/Entites/Project.cs
namespace TaskManagment.Models.Entites
{
    public class Project
    {
        public int ProjectId {  get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public IEnumerable<task>? Tasks { get; set; }
    }
}

Models/Entites/User.cs
namespace TaskManagment.Models.Entites
{
    public class User
    {
        public int Userid {  get; set; }    
        public string Name { get; set; }
        public string Email { get; set; }
        public IEnumerable<task> Tasks { get; set; }
    }
}

Models/Entites/task.cs
using System.ComponentModel.DataAnnotations.Schema;

namespace TaskManagment.Models.Entites
{
    public class task
    {
        public int taskid { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public DateTime StartDate { get; set; }
        public DateTime EndDate { get; set; }
        public string status {  get; set; }
        public int Userid { get; set; }
        [ForeignKey("Userid")]
        public User? User { get; set; }  
        public int Projectid {  get; set; }
        [ForeignKey("Projectid")]
        public Project? Project { get; set; }

    }
}

Models/ErrorViewModel.cs
namespace TaskManagment.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using TaskManagment.Models;

namespace TaskManagment.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/ProjectController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.VisualStudio.Web.CodeGenerators.Mvc.Templates.Blazor;
using TaskManagment.Models.Entites;
using TaskManagment.Repos.Irepo;

namespace TaskManagment.Controllers
{
    public class ProjectController : Controller
    {
        private readonly Iproject iproject;
        public ProjectController(Iproject iproject)
        {
            this.iproject = iproject;
        }
        public async Task<IActionResult> Index()
        {
            var pro = await iproject.GetProjects();
            return View(pro);
        }
        public async Task<IActionResult> Create()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Create(Project p1)
        {
            await iproject.add(p1);
            return RedirectToAction("Index");
        }
        public async Task<IActionResult> Delete(int id)
        {
            var p = await iproject.getby(id);
            return View(p);
        }
        [HttpPost]
        public async Task<IActionResult> Delete(Project project)
        {
            await iproject.delete(project);
            return RedirectToAction("Index");
        }
        public async Task<IActionResult> Edit(int id)
        {
            var p = await iproject.getby(id);
            return View(p);
        }
        [HttpPost]
        public async Task<IActionResult> Edit(Project project)
        {
            await iproject.update(project);
            return RedirectToAction("Index");
        }
    }
}

Controllers/UserController.cs
using Microsoft.AspNetCore.Mvc;
using TaskManagment.Models.Entites;
using TaskManagment.Repos.Irepo;

namespace TaskManagment.Controllers
{
    public class UserController : Controller
    {
        private readonly Iuser iuser;
        public UserController(Iuser iuser)
        {
            this.iuser = iuser;
        }
        public async Task<IActionResult> Index()
        {
            var user = await iuser.GetUsers();
            return View(user);
        }
        public async Task<IActionResult> Create()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Create(User user)
        {
            await iuser.add(user);
            return RedirectToAction("Index");
        }
        public async Task<IActionResult> Delete(int id)
        {
            var user = await iuser.getby(id);
            return View(user);
        }
        [HttpPost]
        public async Task<IActionResult> Delete(User user)
        {
            await iuser.delete(user);
            return RedirectToAction("Index");
        }
        public async Task<IActionResult> Edit(int id)
        {
            var user = await iuser.getby(id);
            return View(user);
        }
        [HttpPost]
        public async Task<IActionResult> Edit(User user)
        {
            await iuser.update(user);   
            return RedirectToAction("Index");
        }
    }
}

Controllers/taskController.cs
using Microsoft.AspNetCore.Mvc;
using NuGet.Packaging.Signing;
using TaskManagment.Models.Entites;
using TaskManagment.Repos.Irepo;
using TaskManagment.ViewModel;

namespace TaskManagment.Controllers
{
    public class taskController : Controller
    {
        private readonly Itask itask;
        private readonly Iproject iproject;
        private readonly Iuser iuser;
        public taskController(Iuser iuser,Iproject iproject,Itask itask)
        {
            this.iuser = iuser;
            this.iproject = iproject;
            this.itask = itask;
        }
        public async Task <IActionResult> Index()
        {
            var t = await itask.GetTasks();
            return View(t);
        }
        public async Task <IActionResult> Create()
        {
            taskViewModel v1 = new taskViewModel()
            {
                projects = await iproject.GetProjects(),
                users = await iuser.GetUsers(),
            };
            return View(v1);
        }
        [HttpPost]
        public async Task<IActionResult> Create(taskViewModel v1)
        {
            await itask.add(v1);
            return RedirectToAction("Index");
        }
        public async Task<IActionResult> Delete(int id)
        {
            var t = await itask.getby(id);
            return View(t);
        }
        [HttpPost]
        public async Task<IActionResult> Delete(task t1)
        {
            await itask.Delete(t1);
            return RedirectToAction("Index");
        }
        public async Task<IActionResult> Edit(int id)
        {
            var v1 = await itask.getby(id);
            taskViewModel t = new taskViewModel()
            {
                projects = await iproject.GetProjects(),
                users = await iuser.GetUsers(),
                Title = v1.Title,
                Description = v1.Description,
                StartDate = v1.StartDate,
                EndDate = v1.EndDate,
                Userid = v1.Userid,
                Projectid = v1.Projectid,
                status = v1.status
            };
            return View(t);
        }
        [HttpPost]
        public async Task<IActionResult> Edit(taskViewModel v1, int id)
        {
            await itask.Edit(v1, id);
            return RedirectToAction("Index");
        }
    }
   
   
}

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Views/Project/Create.cshtml
@model TaskManagment.Models.Entites.Project

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Project</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Project/Delete.cshtml
@model TaskManagment.Models.Entites.Project

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Project</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="ProjectId" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Views/Project/Edit.cshtml
@model TaskManagment.Models.Entites.Project

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Project</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="ProjectId" />
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Project/Index.cshtml
@model IEnumerable<TaskManagment.Models.Entites.Project>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create" class="btn btn-outline-success">Create New</a>
</p>
<table class="table table-striped table-hover">
    <thead class="table table-dark">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Description)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Description)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.ProjectId" class="btn btn-warning">Edit</a> |
                <a asp-action="Delete" asp-route-id="@item.ProjectId" class="btn btn-danger">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - TaskManagment</title>
    <script type="importmap"></script>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/TaskManagment.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">TaskManagment</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="User" asp-action="Index">Users</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Project" asp-action="Index">Projects</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="task" asp-action="Index">Tasks</a>
                        </li>

                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - TaskManagment - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Views/User/Create.cshtml
@model TaskManagment.Models.Entites.User

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>User</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/User/Delete.cshtml
@model TaskManagment.Models.Entites.User

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>User</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Email)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Email)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Userid" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Views/User/Edit.cshtml
@model TaskManagment.Models.Entites.User

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>User</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Userid" />
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/User/Index.cshtml
@model IEnumerable<TaskManagment.Models.Entites.User>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create" class="btn btn-outline-success">Create New</a>
</p>
<table class="table table-striped table-hover">
    <thead class="table table-dark">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Email)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Email)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Userid" class="btn btn-warning">Edit</a> |
                <a asp-action="Delete" asp-route-id="@item.Userid" class="btn btn-danger">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>

Views/task/Create.cshtml
@model TaskManagment.ViewModel.taskViewModel;

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>task</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="StartDate" class="control-label"></label>
                <input asp-for="StartDate" class="form-control" />
                <span asp-validation-for="StartDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="EndDate" class="control-label"></label>
                <input asp-for="EndDate" class="form-control" />
                <span asp-validation-for="EndDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="status" class="control-label"></label>
                <input asp-for="status" class="form-control" />
                <span asp-validation-for="status" class="text-danger"></span>
            </div>
            
            <div class="form-group">
                <label asp-for="Userid" class="control-label"></label>
                <select asp-for="Userid" class ="form-control">
                    @foreach(var user in Model.users)
                    {
                        <option value="@user.Userid">@user.Name</option>
                    }
                </select>
            </div>
            <div class="form-group">
                <label asp-for="Projectid" class="control-label"></label>
                <select asp-for="Projectid" class ="form-control" >
                    @foreach (var p in Model.projects)
                    {
                        <option value="@p.ProjectId">@p.Name</option>
                    }
                </select>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/task/Delete.cshtml
@model TaskManagment.Models.Entites.task

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>task</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Title)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Title)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.StartDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.StartDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.EndDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.EndDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.status)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.status)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.User)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.User.Userid)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Project)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Project.ProjectId)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="taskid" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Views/task/Edit.cshtml
@model TaskManagment.ViewModel.taskViewModel;

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>task</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="taskid" />
            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="StartDate" class="control-label"></label>
                <input asp-for="StartDate" class="form-control" />
                <span asp-validation-for="StartDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="EndDate" class="control-label"></label>
                <input asp-for="EndDate" class="form-control" />
                <span asp-validation-for="EndDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="status" class="control-label"></label>
                <input asp-for="status" class="form-control" />
                <span asp-validation-for="status" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Userid" class="control-label"></label>
                <select asp-for="Userid" class="form-control" asp-items="ViewBag.Userid">
                    @foreach (var user in Model.users)
                    {
                        <option value="@user.Userid">@user.Name</option>
                    }
                </select>
                <span asp-validation-for="Userid" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Projectid" class="control-label"></label>
                <select asp-for="Projectid" class="form-control" asp-items="ViewBag.Projectid">
                    @foreach (var p in Model.projects)
                    {
                        <option value="@p.ProjectId">@p.Name</option>
                    }
                </select>
                <span asp-validation-for="Projectid" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/task/Index.cshtml
@model IEnumerable<TaskManagment.Models.Entites.task>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create" class="btn btn-outline-success">Create New</a>
</p>
<table class="table table-striped table-hover">
    <thead class="table table-dark">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Title)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Description)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.StartDate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.EndDate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.status)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.User)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Project)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Title)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Description)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.StartDate)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.EndDate)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.status)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.User.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Project.Name)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.taskid" class="btn btn-warning">Edit</a> |
                <a asp-action="Delete" asp-route-id="@item.taskid" class="btn btn-danger">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>